### ISSUE TITLE
When receiving data from Cardano node, disconnection occurs intermittently.

### ISSUE THREAD

**Issue by MarMarMot** [bloxbean/yaci-store#263]
I am building the Cardano node from the source code:
https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/getting-started/install.md
and run it in "Preprod" environment. 

In the last few days when I try to get data from the node, I get an error periodically. Each next attempt to retrieve data returns the same error, despite the message “Connection established”.

```
2024-04-25T10:55:37.362Z  INFO 114 --- [ntLoopGroup-5-3] c.b.c.y.s.core.service.CursorService     : # of blocks written: 1
2024-04-25T10:55:37.362Z  INFO 114 --- [ntLoopGroup-5-3] c.b.c.y.s.core.service.CursorService     : Block No: 169863
2024-04-25T10:55:37.374Z  WARN 114 --- [ntLoopGroup-5-3] c.b.c.y.s.a.p.AccountBalanceProcessor    : Account balance calculation will be ignored. Please run the aggregation app to calculate the account balance for pending blocks.
2024-04-25T10:55:37.374Z  WARN 114 --- [ntLoopGroup-5-3] c.b.c.y.s.a.p.AccountBalanceProcessor    : The last processed block for account balance calculation is not the same as the expected last block.
2024-04-25T10:55:37.374Z  WARN 114 --- [ntLoopGroup-5-3] c.b.c.y.s.a.p.AccountBalanceProcessor    : Last processed block for account balance: 15640
2024-04-25T10:55:37.374Z  WARN 114 --- [ntLoopGroup-5-3] c.b.c.y.s.a.p.AccountBalanceProcessor    : Current block: 169864
2024-04-25T10:55:37.375Z  INFO 114 --- [ntLoopGroup-5-3] c.b.c.y.s.core.service.CursorService     : # of blocks written: 1
2024-04-25T10:55:37.375Z  INFO 114 --- [ntLoopGroup-5-3] c.b.c.y.s.core.service.CursorService     : Block No: 169864
2024-04-25T10:57:09.378Z  WARN 114 --- [ntLoopGroup-4-3] i.netty.channel.DefaultChannelPipeline   : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[netty-buffer-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2024-04-25T10:57:09.380Z  INFO 114 --- [ntLoopGroup-4-3] c.b.c.yaci.core.network.NodeClient       : Connection closed !!!
2024-04-25T10:57:09.380Z  INFO 114 --- [ntLoopGroup-4-3] c.b.cardano.yaci.core.network.Session    : Disposing the session !!!
2024-04-25T10:57:09.380Z  WARN 114 --- [ntLoopGroup-4-3] c.b.c.yaci.core.network.NodeClient       : Trying to reconnect !!!
2024-04-25T10:57:09.381Z  INFO 114 --- [ntLoopGroup-4-4] c.b.cardano.yaci.core.network.Session    : Connection established
2024-04-25T10:57:09.381Z  INFO 114 --- [ntLoopGroup-4-4] c.b.c.yaci.core.network.NodeClient       : Connected !!!
2024-04-25T10:57:09.383Z  INFO 114 --- [ntLoopGroup-4-4] c.b.c.y.c.p.handshake.HandshakeAgent     : Handshake Ok!!! AcceptVersion(versionNumber=13, versionData=N2NVersionData(initiatorOnlyDiffusionMode=true, peerSharing=0, query=false))
2024-04-25T10:58:46.379Z  WARN 114 --- [ntLoopGroup-4-4] i.netty.channel.DefaultChannelPipeline   : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[netty-buffer-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2024-04-25T10:58:46.380Z  INFO 114 --- [ntLoopGroup-4-4] c.b.c.yaci.core.network.NodeClient       : Connection closed !!!
2024-04-25T10:58:46.380Z  INFO 114 --- [ntLoopGroup-4-4] c.b.cardano.yaci.core.network.Session    : Disposing the session !!!
2024-04-25T10:58:46.380Z  WARN 114 --- [ntLoopGroup-4-4] c.b.c.yaci.core.network.NodeClient       : Trying to reconnect !!!
2024-04-25T10:58:46.381Z  INFO 114 --- [ntLoopGroup-4-5] c.b.cardano.yaci.core.network.Session    : Connection established
2024-04-25T10:58:46.381Z  INFO 114 --- [ntLoopGroup-4-5] c.b.c.yaci.core.network.NodeClient       : Connected !!!
2024-04-25T10:58:46.381Z  INFO 114 --- [ntLoopGroup-4-5] c.b.c.y.c.p.handshake.HandshakeAgent     : Handshake Ok!!! AcceptVersion(versionNumber=13, versionData=N2NVersionData(initiatorOnlyDiffusionMode=true, peerSharing=0, query=false))
2024-04-25T11:00:23.381Z  WARN 114 --- [ntLoopGroup-4-5] i.netty.channel.DefaultChannelPipeline   : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]

```

After some time the error may disappear and the data starts to load successfully.

**Comment by satran004** [comment]
@MarMarMot Thanks for trying this out.

I have a few questions:

1. Which version of the Yaci store are you using? 0.1.0-rc1?
2. Which app are you using? yaci-store-all, yaci-store-aggregation-app, or yaci-store-utxo-indexer?
3. Could you please share your application properties file? Please remove any database information or passwords before sharing.

From the logs, it seems it has not reached the tip yet. In the main branch, we have fixed a few issues related to connection problems. Ideally, you should not experience connection reset issues during initial sync. However, once it reaches the tip, you may occasionally get a connection reset, but these are harmless.

I also noticed that parallel processing is disabled in your case.
